title: 'Museo Forte Olimpio'
default_lang: it
author:
  name: 'Museo Forte Olimpio'
  email: info@museoforteolimpio.ch
taxonomies:
  - category
  - tag
metadata:
  description: 'Museo Forte Olimpio'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
