title: 'Capanna Gambarögn'
default_lang: it
author:
  name: 'Capanna Gambarögn'
  email: info@capannagambarogno.ch
taxonomies:
  - category
  - tag
metadata:
  description: 'Grav is an easy to use, yet powerful, open source flat-file CMS'
summary:
  enabled: true
  format: short
  size: 300
  delimiter: '==='
blog:
  route: /blog
