version: '3.3'

services:
   grav:
     container_name: grav
     build: docker/grav/
     image: getgrav:1.6.11-php-7.2-apache
     volumes:
      - ${USER_VOLUME}:/var/www/html/user
     ports:
      - "8000:80"
     restart: always
   npm-watch:
     container_name: npm-watch
     build:  docker/npm-watch/
     volumes:
      - ${USER_VOLUME}:/usr/src/app/source